name: Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install kcov
        run: |
          sudo add-apt-repository -y universe
          sudo apt-get update
          sudo apt-get install -y kcov
      - name: Run tests
        run: make test
        shell: bash
      - name: Run coverage
        run: |
          mkdir -p coverage
          kcov --include-path=timers.sh coverage ./tests/test.sh
      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          directory: coverage
